### ISSUE TITLE
docker source causing high IO read/CPU usage

### ISSUE THREAD

**Issue by jerryleooo** [timberio/vector#5404]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
data_dir = "/var/lib/vector"

# Input data. Change me to a valid input source.
[sources.docker]
  type = "docker"

[transforms.add_hostname]
  inputs = ["docker"]
  type   = "add_fields"
  overwrite = true
  fields.hostname = "${INET_IP}"

[transforms.sentry_error]
  inputs = ["add_hostname"]
  type = "filter"
  condition."message.contains" = "error-response"

[transforms.stats]
  inputs = ["add_hostname"]
  type = "filter"
  condition."message.contains" = "stats-"

[sinks.sentry_proxy]
  inputs = ["sentry_error"]
  type   = "http"
  # uri    = "http://127.0.0.1:8100/api/v1/error"
  uri    = "http://insight05.idata-server.shopee.io:10500/api/v1/error"
  encoding.codec = "json" # required

[sinks.es_klog]
  inputs = ["add_hostname"]
  type   = "elasticsearch"
  host   = "${ES_URL}"
  index  = "data-service-api-klog-v1-%Y-%m-%d"

[sinks.es_stats]
  inputs = ["stats"]
  type   = "http"
  # uri    = "http://127.0.0.1:8100/api/v1/stats"
  uri    = "http://insight05.idata-server.shopee.io:10500/api/v1/stats"
  encoding.codec = "json" # required

# Output data
[sinks.out]
  # inputs   = ["sentry_error"]
  inputs = ["docker"]
  type     = "console"
  encoding.codec = "json"
  encoding.only_fields = ["container_name", "message"]
```

### Debug Output

https://gist.github.com/jerryleooo/ec33799e1f86fdab56c792490aa13c14

### Expected Behavior

vector command should not cause high CPU usage / IO read

### Actual Behavior

I use following command to start vector
```
~/.vector/bin/vector -c ~/.vector/config/vector.toml
```

Then I found the CPU usage is high, and IO read is high. **And the situations persists even I stopped vector command**. We have 32 CPU cores, and at the beginning the `dockerd` command occupied around 1400% CPU resources, and now after sometime is drops to 800% as the 3rd pic shows.

![image](https://user-images.githubusercontent.com/3231765/101233025-92549600-36f0-11eb-96bd-8dbafc6194ec.png)
![image](https://user-images.githubusercontent.com/3231765/101233031-997ba400-36f0-11eb-89f5-27144ad92418.png)
![image](https://user-images.githubusercontent.com/3231765/101233040-ae583780-36f0-11eb-9e5c-b46db89b2763.png)

### Additional Context

```
$ docker version                                                                                                                                                  [11:52:30]
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
Linux insight04.idata-server.shopee.io 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jamtur01** [comment]
@jerryleooo Can you please try Vector 0.11 and let us know if the problem still exists?

**Comment by jerryleooo** [comment]
@jamtur01 thanks for the reply, but I still want to make sure it is safe since this is one of our production server. In testing server it is all OK.

I guess the issue may be related to this?
```
Dec 05 11:59:55.896 ERROR vector::sources::docker: Unable to return ContainerLogInfo to main error=channel closed
```

looks like some connection is not properly closed, and I see the change log it is fixed in 0.11.

**Comment by jamtur01** [comment]
@jerryleooo Yes - I believe it is fixed in 0.11. Please let us know when you get to test it and re-open if you find more issues. Thanks!

**Comment by jerryleooo** [comment]
@jamtur01 currently I am using 0.12, seems there is still the same error when shutting down vector: https://gist.github.com/jerryleooo/6a892e831743145fb85c473934637f84

```
work@insight05: ~
$ vector --version                                                                                                                                                [16:00:37]
vector 0.12.0 (g945706e x86_64-unknown-linux-musl 2020-12-05)
```

**Comment by jerryleooo** [comment]
with 0.11.0 the high IO/CPU load issue still persists. Reopening the issue.

**Comment by jerryleooo** [comment]
Not sure if it is related to my machine IO configuration, since in another machine it works fine

**Comment by jamtur01** [comment]
@jerryleooo So it works on one host but you get IO on another? Any difference between the hosts?

**Comment by jerryleooo** [comment]
@jamtur01 they should be almost the same, CPU, Memory, and even the number of containers. One is our production server and another is not. The only difference maybe traffic? (production one has more traffic)

I checked the monitoring and find the problem is high IO wait, wondering what configuration would cause that?

**Comment by ktff** [comment]
> I guess the issue may be related to this?
>
> `Dec 05 11:59:55.896 ERROR vector::sources::docker: Unable to return ContainerLogInfo to main error=channel closed`
>
> looks like some connection is not properly closed, and from the change log I see it is fixed in 0.11.

That isn't the cause because it's perfectly normal to happen when shutting down the source, so that actually shouldn't be an `ERROR` but a `DEBUG`.

> they should be almost the same, CPU, Memory, and even the number of containers. One is our production server and another is not.

@jerryleooo does the issue happen on the host that has been running the longest/has the most logs? If yes, the problem is probably in the older logs which `dockerd` is picking up for some reason. We are requesting only the newer logs, so this would indicate that there is either a bug in `bollard` or `dockerd` needs to process all of the logs for some reason, compression maybe.

**Comment by nivekuil** [comment]
Could this be related? https://github.com/docker/for-linux/issues/641 What does your logging configuration look like for the docker containers?

**Comment by ktff** [comment]
@jerryleooo the issue docker/for-linux#641 that @nivekuil mentioned is most likely the cause, which also explains the behavioral difference between your production and testing servers. More precisely, this [comment](https://github.com/docker/for-linux/issues/641#issuecomment-665377103) seams as most relevant for this issue, so could you try out the solution mentioned in the comment and report the results?

**Comment by ktff** [comment]
I'll be closing this issue. @jerryleooo when you do get around in checking https://github.com/timberio/vector/issues/5404#issuecomment-757549079 do report it here and we'll reopen the issue if needed.

Locally I've been able to reproduce the issue by generating a large log file with one container and then starting Vector to listen on that container. We aren't requesting the older logs so I believe this is an issue of `dockerd` seeking into the log file linearly trying to find the first log we requested.

This is an issue of `json-file` logging driver, but in extension it's also an issue of `docker` source. Here are some ways to ease the problem:
* Use `journald` logging driver.
* Follow advice in https://github.com/docker/for-linux/issues/641#issuecomment-665377103.
* In situations like this avoid having Vector in agent role, and instead opt for sidecar role. These two can be mix matched depending on what containers are more or less problematic.

Any of the above will solve the issue.

We can also consider moving away from Docker API and collecting logs our self via `file` source and `journald` source. Although that has it's own disadvantages. 

cc. @binarylogic
