### ISSUE TITLE
Nightly releases broken

### ISSUE THREAD

**Issue by cmmarslender** [timberio/vector#956]
Hello,

The release at https://packages.timber.io/vector/nightly/latest/vector-x86_64-unknown-linux-musl.tar.gz doesn't appear to be working.. That url is currently showing a server index page instead.

**Comment by cmmarslender** [comment]
<img width="536" alt="vector" src="https://user-images.githubusercontent.com/1915905/66007769-858f3f00-e468-11e9-8e12-312d760d9304.PNG">

**Comment by binarylogic** [comment]
Thanks @cmmarslender, sorry for the inconvenience. This should be resolved now. We made some infrastructure changes that broke our IAM permissions for the underlying S3 bucket.

**Comment by cmmarslender** [comment]
@binarylogic I'm still seeing the same behavior.. in browser, its showing the server index page and if I try to pull the file with wget or curl, I just get a 403.

**Comment by binarylogic** [comment]
Ah damn, sorry about that. I'm fixing and adding a verification step as part of our CI process.

**Comment by binarylogic** [comment]
Hi @cmmarslender , this should be resolved now. I've manually verified that we can download the latest nightly files. In addition, we added verification steps in https://github.com/timberio/vector/pull/961 and https://github.com/timberio/vector/pull/961. This should ensure we don't regress on this.
